apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-db-credentials
  annotations:
    kubernetes.io/service-account.name: "ksa"
stringData:
  username: wordpress_sql_user
  password: gke_sql_wordpress_pass